name: Deploy Pulumi AWS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# ESSENCIAL: Permite que o GitHub solicite o token OIDC
permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Código
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar Dependências
        run: npm install

      - name: Configurar Credenciais AWS via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::211125336427:role/oidc_github
          aws-region: us-east-1

      - name: Pulumi Action
        uses: pulumi/actions@v5
        with:
          command: ${{ github.event_name == 'pull_request' && 'preview' || 'up' }}
          stack-name: jnetoass-org/meu-pulumi/dev
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          # As variáveis AWS_ACCESS_KEY_ID, etc., são injetadas automaticamente pelo step anterior