name: Deploy Pulumi AWS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Evita conflitos de concorrência e economiza minutos de execução
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write      # Necessário para OIDC AWS
  contents: read       # Necessário para Checkout
  pull-requests: write # Necessário para Comentários do Pulumi no PR

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Código
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Instalar Dependências
        run: npm ci # 'npm ci' é mais rápido e seguro que 'install' em CI/CD

      - name: Configurar Credenciais AWS via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::211125336427:role/oidc_github
          aws-region: us-east-1

      - name: Pulumi Action
        uses: pulumi/actions@v5
        with:
          command: ${{ github.event_name == 'pull_request' && 'preview' || 'up' }}
          stack-name: jnetoass-org/meu-pulumi/dev
          comment-on-pr: true
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}