name: Deploy Pulumi AWS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  # Job 1: Sempre gera o Preview para análise
  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci
      - name: Configurar AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::730335657713:role/oidc_github
          aws-region: us-east-1
      - name: Pulumi Preview
        uses: pulumi/actions@v5
        with:
          command: preview
          stack-name: jnetoass-org/meu-pulumi/dev
          comment-on-pr: true
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

  # Job 2: Só roda na 'main' e EXIGE aprovação manual
  deploy:
    runs-on: ubuntu-latest
    needs: preview             # Espera o preview terminar
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    environment: production    # <--- A "mágica" acontece aqui
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci
      - name: Configurar AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::730335657713:role/oidc_github
          aws-region: us-east-1
      - name: Pulumi Up
        uses: pulumi/actions@v5
        with:
          command: up
          stack-name: jnetoass-org/meu-pulumi/dev
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}